config/routes.rb
Rails.application.routes.draw do
  # get 'review/new'
  # get 'review/create'
  # get 'restaurants/index'
  # get 'restaurants/new'
  # get 'restaurants/create'
  # get 'restaurants/show'
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian) }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
    @reviews = @restaurant.reviews
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to restaurant_path(@review.restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container">
  <%= simple_form_for(@restaurant) do |r| %>
    <%= r.input :name %>
    <%= r.input :address %>
    <%= r.input :phone_number %>
    <%= r.submit "modify a restaurant", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/restaurants/edit.html.erb
<!-- <h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p> -->
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<!-- <h1>Restaurants#index</h1>
<p>Find me in app/views/restaurants/index.html.erb</p> -->
<% @restaurants.each do |r| %>
<div class="card">
<p><%= link_to r[:name], restaurant_path(r.id) %></p>
<p><%= r.address %></p>
</div>
<% end %>

<div class="container">
  <%= link_to "add a new restaurant",  new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<!-- <h1>Restaurants#new</h1>
<p>Find me in app/views/restaurants/new.html.erb</p> -->
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<!-- <h1>Restaurants#show</h1>
<p>Find me in app/views/restaurants/show.html.erb</p> -->
<div class="card">
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p> <p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category %></p>
</div>

<p><% @reviews.each do |t| %></p>
<div class="card-review">
   <p><%= t.content %></p>
   <p><%= t.rating.times do %></p>🥕
   <% end %>
</div>
<% end %>

<div class="container">
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "add a review", class: "btn btn-primary" %>
  <% end %>

  <p><%= link_to "edit",  edit_restaurant_path(@restaurant) %></p>

  <%= link_to restaurant_path(@restaurant.id),
        method: :delete,
        data: { confirm: "Are you sure?" } do %> <i class="fas fa-dumpster-fire"></i> <% end %>

  <p><%= link_to 'back to list', restaurants_path %></p>
</div>

app/views/reviews/create.html.erb
<!-- <h1>Review#create</h1>
<p>Find me in app/views/review/create.html.erb</p> -->
<%= render 'form', review: @review %>

app/views/reviews/new.html.erb
<!-- <h1>Review#new</h1>
<p>Find me in app/views/review/new.html.erb</p> -->

<%= render 'form', review: @review %>